debug: true
spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

